// =================================================================
// LED Matrix Studio - (c) Paul A Freshney 2015
// 
// www.MaximumOctopus.com
// www.MaximumOctopus.com/electronics/builder.htm
// 
// Date : 04/03/2019
// 
// -----------------------------------------------------------------
// Original file:
//  C:\Users\Ryan\Downloads\LEDMatrixStudio\LEDMatrixStudio\saves\alphabet.leds
// 
// =================================================================
// 
// Animation Frames #1 to #29
// 
// =================================================================
// 
// Source : Rows
// Line   : Row
// Bits   : LSB at left
// Order  : Top to bottom
// Scan   : Left to right
// Size   : 8 bits
// 
// =================================================================
#define ALPHA_WIDTH 5

byte alpha_array[] = {
                   0x04, 
                   0x0A, 
                   0x11, 
                   0x1F, 
                   0x11, 
                   0x11, 
                   0x0F, 
                   0x0B, 
                   0x1F, 
                   0x13, 
                   0x13, 
                   0x1F, 
                   0x1F, 
                   0x03, 
                   0x03, 
                   0x03, 
                   0x03, 
                   0x1F, 
                   0x0F, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x0F, 
                   0x1F, 
                   0x03, 
                   0x1F, 
                   0x03, 
                   0x03, 
                   0x1F, 
                   0x1F, 
                   0x03, 
                   0x0F, 
                   0x03, 
                   0x03, 
                   0x03, 
                   0x1F, 
                   0x03, 
                   0x03, 
                   0x1B, 
                   0x13, 
                   0x1F, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x1F, 
                   0x13, 
                   0x13, 
                   0x1F, 
                   0x0C, 
                   0x0C, 
                   0x0C, 
                   0x0C, 
                   0x1F, 
                   0x1C, 
                   0x18, 
                   0x18, 
                   0x18, 
                   0x1B, 
                   0x1F, 
                   0x1B, 
                   0x1B, 
                   0x0F, 
                   0x0F, 
                   0x1B, 
                   0x1B, 
                   0x03, 
                   0x03, 
                   0x03, 
                   0x03, 
                   0x03, 
                   0x1F, 
                   0x1B, 
                   0x1B, 
                   0x15, 
                   0x11, 
                   0x11, 
                   0x11, 
                   0x13, 
                   0x13, 
                   0x17, 
                   0x1B, 
                   0x13, 
                   0x13, 
                   0x1F, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x1F, 
                   0x1F, 
                   0x13, 
                   0x1F, 
                   0x03, 
                   0x03, 
                   0x03, 
                   0x1F, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x1F, 
                   0x10, 
                   0x1F, 
                   0x13, 
                   0x13, 
                   0x1F, 
                   0x0B, 
                   0x13, 
                   0x1F, 
                   0x03, 
                   0x1F, 
                   0x10, 
                   0x10, 
                   0x1F, 
                   0x1F, 
                   0x04, 
                   0x04, 
                   0x04, 
                   0x04, 
                   0x04, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x1F, 
                   0x13, 
                   0x13, 
                   0x13, 
                   0x1B, 
                   0x0E, 
                   0x06, 
                   0x11, 
                   0x11, 
                   0x15, 
                   0x15, 
                   0x15, 
                   0x0A, 
                   0x11, 
                   0x1B, 
                   0x0E, 
                   0x0E, 
                   0x1B, 
                   0x11, 
                   0x11, 
                   0x11, 
                   0x1B, 
                   0x0E, 
                   0x04, 
                   0x04, 
                   0x1F, 
                   0x18, 
                   0x0C, 
                   0x06, 
                   0x03, 
                   0x1F, 
                   0x04, 
                   0x04, 
                   0x04, 
                   0x04, 
                   0x00, 
                   0x04, 
                   0x0E, 
                   0x11, 
                   0x0C, 
                   0x04, 
                   0x00, 
                   0x04, 
                   0x04, 
                   0x0E, 
                   0x05, 
                   0x0E, 
                   0x14, 
                   0x0E, 
                   0x00, 
                   0x00, 
                   0x00, 
                   0x00, 
                   0x00, 
                   0x00, 
                   };
// 
// =================================================================
// 

